# tensor

In [1]:
import torch

In [2]:
x = torch.tensor([[1, -1],
                 [1, -1]])
x

tensor([[ 1, -1],
        [ 1, -1]])

In [3]:
x = torch.zeros([2, 2])
x

tensor([[0., 0.],
        [0., 0.]])

In [4]:
x = torch.ones([1, 2, 2])
x

tensor([[[1., 1.],
         [1., 1.]]])

In [5]:
x = torch.zeros([1, 2, 3])
y = torch.ones([2, 2, 3])
w = torch.cat([x,y], dim = 0)
w

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [6]:
x = torch.zeros([1, 3])
y = torch.ones([2, 3])
w = torch.cat([x,y], dim = 0)
w

tensor([[0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
import torch
from torch.autograd import variable

In [8]:
x  = torch.rand(1)
x

tensor([0.1304])

In [9]:
x = variable(x, requires_grad = True)
x

G:\anaconda\lib\site-packages\torch\autograd\__init__.py:167: UserWarning: torch.autograd.variable(...) is deprecated, use torch.tensor(...) instead
  warnings.warn("torch.autograd.variable(...) is deprecated, use torch.tensor(...) instead")
G:\anaconda\lib\site-packages\torch\autograd\__init__.py:168: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(*args, **kwargs)


tensor([0.1304], requires_grad=True)

In [10]:
z = torch.tensor([2.], requires_grad = True)

In [11]:
y = x * 3 + z
y

tensor([2.3913], grad_fn=<AddBackward0>)

In [12]:
gv = torch.FloatTensor([1,2,3,4])
gv

tensor([1., 2., 3., 4.])

In [13]:
y.backward()

In [14]:
x.grad

tensor([3.])

In [15]:
z.grad

tensor([1.])

In [16]:
y.grad

In [17]:
x

tensor([0.1304], requires_grad=True)

# index

In [18]:
a = torch.rand(4,3,28,28)

In [19]:
a.shape

torch.Size([4, 3, 28, 28])

In [20]:
a = torch.tensor([1.2,2.3])

In [21]:
a

tensor([1.2000, 2.3000])

In [22]:
a.unsqueeze(0).shape

torch.Size([1, 2])

In [23]:
a.unsqueeze(1).shape

torch.Size([2, 1])

In [24]:
b = torch.rand(32)
b

tensor([0.1858, 0.3338, 0.8556, 0.9895, 0.9082, 0.9028, 0.2599, 0.9968, 0.3247,
        0.3803, 0.5160, 0.5066, 0.3223, 0.3402, 0.1788, 0.2181, 0.5389, 0.3765,
        0.6282, 0.8035, 0.8355, 0.0916, 0.8614, 0.4159, 0.1683, 0.6149, 0.4180,
        0.3253, 0.7010, 0.2683, 0.5599, 0.6126])

In [25]:
b.unsqueeze(1).unsqueeze(2).shape

torch.Size([32, 1, 1])

In [26]:
b = torch.rand(32,1,1)

In [27]:
b.shape

torch.Size([32, 1, 1])

In [28]:
b.squeeze().shape

torch.Size([32])

In [29]:
b.squeeze(1).shape

torch.Size([32, 1])

In [30]:
b.squeeze(0).shape

torch.Size([32, 1, 1])

# expand

In [31]:
a = torch.rand(4, 32, 14, 14)
b = torch.rand(1, 32, 1, 1)
b.shape

torch.Size([1, 32, 1, 1])

In [32]:
b.expand(4,32,14,14)

tensor([[[[0.1496, 0.1496, 0.1496,  ..., 0.1496, 0.1496, 0.1496],
          [0.1496, 0.1496, 0.1496,  ..., 0.1496, 0.1496, 0.1496],
          [0.1496, 0.1496, 0.1496,  ..., 0.1496, 0.1496, 0.1496],
          ...,
          [0.1496, 0.1496, 0.1496,  ..., 0.1496, 0.1496, 0.1496],
          [0.1496, 0.1496, 0.1496,  ..., 0.1496, 0.1496, 0.1496],
          [0.1496, 0.1496, 0.1496,  ..., 0.1496, 0.1496, 0.1496]],

         [[0.6245, 0.6245, 0.6245,  ..., 0.6245, 0.6245, 0.6245],
          [0.6245, 0.6245, 0.6245,  ..., 0.6245, 0.6245, 0.6245],
          [0.6245, 0.6245, 0.6245,  ..., 0.6245, 0.6245, 0.6245],
          ...,
          [0.6245, 0.6245, 0.6245,  ..., 0.6245, 0.6245, 0.6245],
          [0.6245, 0.6245, 0.6245,  ..., 0.6245, 0.6245, 0.6245],
          [0.6245, 0.6245, 0.6245,  ..., 0.6245, 0.6245, 0.6245]],

         [[0.8923, 0.8923, 0.8923,  ..., 0.8923, 0.8923, 0.8923],
          [0.8923, 0.8923, 0.8923,  ..., 0.8923, 0.8923, 0.8923],
          [0.8923, 0.8923, 0.8923,  ..., 0

# repeat

In [33]:
b.shape

torch.Size([1, 32, 1, 1])

In [34]:
b.repeat(4,1,1,1).shape

torch.Size([4, 32, 1, 1])

In [35]:
b.repeat(4,32,1,1).shape

torch.Size([4, 1024, 1, 1])

In [36]:
b.repeat(4,32,32,1).shape

torch.Size([4, 1024, 32, 1])

# transpose

In [37]:
a = torch.rand(3,4)

In [38]:
a

tensor([[0.5180, 0.9785, 0.3337, 0.0848],
        [0.1181, 0.5535, 0.0031, 0.5742],
        [0.1952, 0.7378, 0.5811, 0.6997]])

In [39]:
a.t().shape

torch.Size([4, 3])

In [40]:
a = torch.rand(4,3,32,32)

In [41]:
a1 = a.transpose(1,3).view(4, 3*32*32)

RuntimeError: invalid argument 2: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Call .contiguous() before .view(). at c:\n\pytorch_1559129895673\work\aten\src\th\generic/THTensor.cpp:213

In [42]:
a1 = a.transpose(1,3).contiguous().view(4, 3*32*32).view(4,3,32,32)
a1

tensor([[[[5.7385e-01, 6.3845e-01, 4.5204e-01,  ..., 8.8682e-01,
           3.2591e-01, 4.2463e-01],
          [2.3693e-01, 4.2497e-02, 4.7741e-02,  ..., 6.6625e-01,
           1.9454e-01, 8.2723e-02],
          [8.0871e-01, 3.0972e-01, 5.4702e-01,  ..., 7.4332e-01,
           1.4993e-02, 9.7350e-02],
          ...,
          [7.2369e-02, 5.4630e-01, 8.2269e-01,  ..., 8.0223e-01,
           9.4989e-01, 3.4665e-01],
          [4.3688e-01, 4.6789e-01, 9.6422e-01,  ..., 8.1024e-01,
           4.6508e-01, 5.5383e-01],
          [3.2173e-01, 8.0926e-01, 7.1899e-01,  ..., 7.6759e-01,
           7.4610e-01, 4.1486e-01]],

         [[7.3367e-01, 2.9152e-01, 3.6707e-01,  ..., 2.9545e-01,
           1.5578e-01, 3.8320e-01],
          [7.2420e-01, 6.4840e-01, 5.6186e-01,  ..., 9.1679e-01,
           9.8373e-01, 8.8249e-02],
          [9.0112e-02, 9.7532e-01, 2.5745e-01,  ..., 9.7865e-01,
           8.7225e-01, 7.9973e-01],
          ...,
          [9.4433e-01, 1.2555e-01, 4.5855e-02,  ..., 9.6510

In [43]:
a2 = a.transpose(1,3).contiguous().view(4, 3*32*32).view(4,32,32,3).transpose(1,3)
a2

tensor([[[[5.7385e-01, 5.8190e-01, 9.3117e-01,  ..., 7.3423e-02,
           2.7884e-01, 9.3440e-01],
          [1.8866e-01, 5.6286e-01, 4.9561e-02,  ..., 6.0080e-01,
           3.6017e-01, 7.8093e-01],
          [7.9034e-01, 6.7670e-01, 4.8535e-01,  ..., 7.3898e-02,
           8.8660e-01, 4.2429e-01],
          ...,
          [1.4837e-01, 4.4628e-01, 7.2883e-01,  ..., 6.0168e-01,
           3.2467e-01, 2.7953e-01],
          [7.9934e-01, 7.5804e-01, 2.9609e-01,  ..., 1.2989e-01,
           3.4538e-01, 8.6129e-01],
          [7.4332e-01, 4.1216e-01, 1.2867e-01,  ..., 4.1625e-02,
           7.3800e-01, 9.2826e-01]],

         [[6.3845e-01, 4.9436e-01, 4.9745e-02,  ..., 7.6776e-01,
           5.3442e-01, 3.1478e-01],
          [9.6696e-01, 1.7660e-01, 6.4382e-01,  ..., 3.5807e-01,
           5.9412e-01, 7.1275e-01],
          [3.9529e-02, 2.0213e-01, 6.1713e-01,  ..., 9.4807e-01,
           9.1558e-01, 7.0901e-01],
          ...,
          [7.6091e-01, 2.0432e-02, 7.5290e-01,  ..., 1.2442

In [44]:
torch.all(torch.eq(a,a1))

tensor(0, dtype=torch.uint8)

In [45]:
torch.all(torch.eq(a,a2))

tensor(1, dtype=torch.uint8)

# permute

In [46]:
b.shape

torch.Size([1, 32, 1, 1])

In [47]:
b.permute(0,2,3,1).shape

torch.Size([1, 1, 1, 32])