# where

In [1]:
import torch

In [2]:
judge = torch.rand(2,2)
judge

tensor([[0.4464, 0.5871],
        [0.2826, 0.3887]])

In [3]:
a = torch.zeros(2,2)
b = torch.ones(2,2)

In [4]:
torch.where(judge>0.5, a, b)

tensor([[1., 0.],
        [1., 1.]])

# gather

In [5]:
norm = torch.randn(3,4)
norm

tensor([[-0.8116,  0.5221, -0.4875,  1.7897],
        [-0.2118, -1.8273, -0.9981, -0.3536],
        [-2.0495,  0.5185, -0.2931, -1.8170]])

In [6]:
ind = norm.topk(k = 2)[1]
ind

tensor([[3, 1],
        [0, 3],
        [1, 2]])

In [7]:
ex_gather = torch.arange(4)+10
ex_gather.expand(3,4)

tensor([[10, 11, 12, 13],
        [10, 11, 12, 13],
        [10, 11, 12, 13]])

In [8]:
torch.gather(ex_gather.expand(3,4), dim = 1, index = ind)

tensor([[13, 11],
        [10, 13],
        [11, 12]])